# Generated by Django 6.0 on 2026-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.IntegerField(default=0),
        ),
    ]
